### ISSUE TITLE
WiFi auth issues and core panic sending on BLE serial

### ISSUE THREAD

**Issue by al-heisner** [antirez/freakwan#14]
I'll start by saying this is my first LoRa microcontroller and my first experience with micropython. And, thank you for sharing this project and your work. 

After struggling with this for a full day, I realize I may need some help getting it going. I spent most of the day troubleshooting why it wouldn't connect to my WiFi. I could boot up mpy with no main.py and join wifi from REPL, but when booted to freakwan the WLAN interface would repeatedly bounce from "connecting" to "bad auth" state. I eventually discovered that mpy version v1.21.0 and v1.22.0-preview.254 are unable to join WiFi from freakwan but v1.20.0 was. Unfortunately mpy v1.20.0 seems to have it's own issues, like core panic when attempting to send over BLE serial.

All that struggle with WiFi and BLE serial brings me to the question - What version of mpy can be used to minimize these issues, or what mpy version was freakwan developed / tested on?

**Comment by antirez** [comment]
Hi, not sure about the WiFi but the BLE thing is a matter of downgrading MicroPython to older versions.

**Comment by antirez** [comment]
Should be v1.19.1 if I recall correctly.

**Comment by al-heisner** [comment]
will test with 1.19.1 and report back then ;-)

**Comment by al-heisner** [comment]
BLE send and WiFi are both working in mpy v1.19.1, ty!

**Comment by antirez** [comment]
Great!
