### ISSUE TITLE
no module named fci.ImageFCI

### ISSUE THREAD

**Issue by vladbondarenko** [antirez/freakwan#6]
Hello,

im trying to run freakwan on esp32s3, uploaded repo to the board but cant get it working

>>> %Run -c $EDITOR_CONTENT
Traceback (most recent call last):
  File "<stdin>", line 8, in <module>
  File "freakwan.py", line 11, in <module>
  File "scroller.py", line 8, in <module>
ImportError: no module named 'fci.ImageFCI'
>>> 

micropython GENERIC_S3-20220618-v1.19.1.bin
Thonny 4.0.2
Ubuntu 22

any ideas?

Thanks.

**Comment by vladbondarenko** [comment]
Hi,

Yes, talk32 uploads fine and its working now, realy strange.

BTW, is there an option to implement support for SX1262 also? 
it has additional "Busy" pin and DIO1 instead of DIO0

**Comment by antirez** [comment]
Yes, I'm implementing support for the sx1262 as well. For now in the C implementation for the T-Beam but later with Python as well, as soon as I get my hands on an esp32 module with the sx1262 on board.

**Comment by vladbondarenko** [comment]
ok, thanks a lot, will wait.
